version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - ORIENT_DB_HOST=orientdb
#      DB_HOST: postgres

  orientdb:
    image: orientdb:3.2.14-tp3
    container_name: orientdb
    environment:
      - ORIENTDB_ROOT_USER=root
      - ORIENTDB_ROOT_PASSWORD=root
    ports:
      - "2424:2424"
      - "2480:2480"
    restart: on-failure

#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      # - POSTGRES_DB=postgres
#    ports:
#      - "5432:5432"
#    restart: on-failure

